services:
  icecast:
    image: libretime/icecast:2.4.4-debian
    ports:
      - 8000:8000
    volumes:
      - ./icecast.xml:/etc/icecast.xml
  sm2:
    image: savonet/liquidsoap:v2.3.0
#   change this for whatever you want to test
#    command: -v StationManager2.liq -- stationconfig.json
#    command: -v test_speech.liq
    command: -v test_track_filtering.liq

    ports:
#      - 1447:1447
      - 1234:1234
    working_dir: /sm2
    volumes:
      - ./:/sm2
      - /tmp/:/tmp
    environment:
      - "Etc/UTC"
